//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace UpdateStatusTest.inboundserv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IInboundService", Namespace="http://tempuri.org/")]
    public partial class InboundService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StartCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartCallToAgentOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsAgentReadyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCrmStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartCallToAgentFromKCMOperationCompleted;
        
        private System.Threading.SendOrPostCallback CIFAOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartCallMeUrgentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInboundUserCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartNewCallOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InboundService() {
            this.Url = global::UpdateStatusTest.Properties.Settings.Default.UpdateStatusTest_inboundserv_InboundService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StartCallCompletedEventHandler StartCallCompleted;
        
        /// <remarks/>
        public event StartCallToAgentCompletedEventHandler StartCallToAgentCompleted;
        
        /// <remarks/>
        public event IsAgentReadyCompletedEventHandler IsAgentReadyCompleted;
        
        /// <remarks/>
        public event UpdateCrmStatusCompletedEventHandler UpdateCrmStatusCompleted;
        
        /// <remarks/>
        public event StartCallToAgentFromKCMCompletedEventHandler StartCallToAgentFromKCMCompleted;
        
        /// <remarks/>
        public event CIFACompletedEventHandler CIFACompleted;
        
        /// <remarks/>
        public event StartCallMeUrgentCompletedEventHandler StartCallMeUrgentCompleted;
        
        /// <remarks/>
        public event UpdateInboundUserCountCompletedEventHandler UpdateInboundUserCountCompleted;
        
        /// <remarks/>
        public event StartNewCallCompletedEventHandler StartNewCallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/StartCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InboundResult StartCall([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string menuNo) {
            object[] results = this.Invoke("StartCall", new object[] {
                        phoneNumber,
                        menuNo});
            return ((InboundResult)(results[0]));
        }
        
        /// <remarks/>
        public void StartCallAsync(string phoneNumber, string menuNo) {
            this.StartCallAsync(phoneNumber, menuNo, null);
        }
        
        /// <remarks/>
        public void StartCallAsync(string phoneNumber, string menuNo, object userState) {
            if ((this.StartCallOperationCompleted == null)) {
                this.StartCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartCallOperationCompleted);
            }
            this.InvokeAsync("StartCall", new object[] {
                        phoneNumber,
                        menuNo}, this.StartCallOperationCompleted, userState);
        }
        
        private void OnStartCallOperationCompleted(object arg) {
            if ((this.StartCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartCallCompleted(this, new StartCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/StartCallToAgent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InboundResult StartCallToAgent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agentId) {
            object[] results = this.Invoke("StartCallToAgent", new object[] {
                        phoneNumber,
                        agentId});
            return ((InboundResult)(results[0]));
        }
        
        /// <remarks/>
        public void StartCallToAgentAsync(string phoneNumber, string agentId) {
            this.StartCallToAgentAsync(phoneNumber, agentId, null);
        }
        
        /// <remarks/>
        public void StartCallToAgentAsync(string phoneNumber, string agentId, object userState) {
            if ((this.StartCallToAgentOperationCompleted == null)) {
                this.StartCallToAgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartCallToAgentOperationCompleted);
            }
            this.InvokeAsync("StartCallToAgent", new object[] {
                        phoneNumber,
                        agentId}, this.StartCallToAgentOperationCompleted, userState);
        }
        
        private void OnStartCallToAgentOperationCompleted(object arg) {
            if ((this.StartCallToAgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartCallToAgentCompleted(this, new StartCallToAgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/IsAgentReady", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MsCrmResult IsAgentReady([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agentId) {
            object[] results = this.Invoke("IsAgentReady", new object[] {
                        agentId});
            return ((MsCrmResult)(results[0]));
        }
        
        /// <remarks/>
        public void IsAgentReadyAsync(string agentId) {
            this.IsAgentReadyAsync(agentId, null);
        }
        
        /// <remarks/>
        public void IsAgentReadyAsync(string agentId, object userState) {
            if ((this.IsAgentReadyOperationCompleted == null)) {
                this.IsAgentReadyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAgentReadyOperationCompleted);
            }
            this.InvokeAsync("IsAgentReady", new object[] {
                        agentId}, this.IsAgentReadyOperationCompleted, userState);
        }
        
        private void OnIsAgentReadyOperationCompleted(object arg) {
            if ((this.IsAgentReadyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAgentReadyCompleted(this, new IsAgentReadyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/UpdateCrmStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MsCrmResult UpdateCrmStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agentId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string centralStatus) {
            object[] results = this.Invoke("UpdateCrmStatus", new object[] {
                        agentId,
                        centralStatus});
            return ((MsCrmResult)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCrmStatusAsync(string agentId, string centralStatus) {
            this.UpdateCrmStatusAsync(agentId, centralStatus, null);
        }
        
        /// <remarks/>
        public void UpdateCrmStatusAsync(string agentId, string centralStatus, object userState) {
            if ((this.UpdateCrmStatusOperationCompleted == null)) {
                this.UpdateCrmStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCrmStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateCrmStatus", new object[] {
                        agentId,
                        centralStatus}, this.UpdateCrmStatusOperationCompleted, userState);
        }
        
        private void OnUpdateCrmStatusOperationCompleted(object arg) {
            if ((this.UpdateCrmStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCrmStatusCompleted(this, new UpdateCrmStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/StartCallToAgentFromKCM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InboundResult StartCallToAgentFromKCM([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agentId) {
            object[] results = this.Invoke("StartCallToAgentFromKCM", new object[] {
                        phoneNumber,
                        agentId});
            return ((InboundResult)(results[0]));
        }
        
        /// <remarks/>
        public void StartCallToAgentFromKCMAsync(string phoneNumber, string agentId) {
            this.StartCallToAgentFromKCMAsync(phoneNumber, agentId, null);
        }
        
        /// <remarks/>
        public void StartCallToAgentFromKCMAsync(string phoneNumber, string agentId, object userState) {
            if ((this.StartCallToAgentFromKCMOperationCompleted == null)) {
                this.StartCallToAgentFromKCMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartCallToAgentFromKCMOperationCompleted);
            }
            this.InvokeAsync("StartCallToAgentFromKCM", new object[] {
                        phoneNumber,
                        agentId}, this.StartCallToAgentFromKCMOperationCompleted, userState);
        }
        
        private void OnStartCallToAgentFromKCMOperationCompleted(object arg) {
            if ((this.StartCallToAgentFromKCMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartCallToAgentFromKCMCompleted(this, new StartCallToAgentFromKCMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/CIFA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MsCrmResult CIFA([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectedAgentId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string selectedAgentId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string URL, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string callId) {
            object[] results = this.Invoke("CIFA", new object[] {
                        connectedAgentId,
                        selectedAgentId,
                        URL,
                        phoneNo,
                        callId});
            return ((MsCrmResult)(results[0]));
        }
        
        /// <remarks/>
        public void CIFAAsync(string connectedAgentId, string selectedAgentId, string URL, string phoneNo, string callId) {
            this.CIFAAsync(connectedAgentId, selectedAgentId, URL, phoneNo, callId, null);
        }
        
        /// <remarks/>
        public void CIFAAsync(string connectedAgentId, string selectedAgentId, string URL, string phoneNo, string callId, object userState) {
            if ((this.CIFAOperationCompleted == null)) {
                this.CIFAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCIFAOperationCompleted);
            }
            this.InvokeAsync("CIFA", new object[] {
                        connectedAgentId,
                        selectedAgentId,
                        URL,
                        phoneNo,
                        callId}, this.CIFAOperationCompleted, userState);
        }
        
        private void OnCIFAOperationCompleted(object arg) {
            if ((this.CIFACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CIFACompleted(this, new CIFACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/StartCallMeUrgent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InboundResult StartCallMeUrgent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string menuNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string agentId) {
            object[] results = this.Invoke("StartCallMeUrgent", new object[] {
                        phoneNumber,
                        menuNo,
                        agentId});
            return ((InboundResult)(results[0]));
        }
        
        /// <remarks/>
        public void StartCallMeUrgentAsync(string phoneNumber, string menuNo, string agentId) {
            this.StartCallMeUrgentAsync(phoneNumber, menuNo, agentId, null);
        }
        
        /// <remarks/>
        public void StartCallMeUrgentAsync(string phoneNumber, string menuNo, string agentId, object userState) {
            if ((this.StartCallMeUrgentOperationCompleted == null)) {
                this.StartCallMeUrgentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartCallMeUrgentOperationCompleted);
            }
            this.InvokeAsync("StartCallMeUrgent", new object[] {
                        phoneNumber,
                        menuNo,
                        agentId}, this.StartCallMeUrgentOperationCompleted, userState);
        }
        
        private void OnStartCallMeUrgentOperationCompleted(object arg) {
            if ((this.StartCallMeUrgentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartCallMeUrgentCompleted(this, new StartCallMeUrgentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/UpdateInboundUserCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MsCrmResult UpdateInboundUserCount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string queueNo, int inboundUserCount, [System.Xml.Serialization.XmlIgnoreAttribute()] bool inboundUserCountSpecified) {
            object[] results = this.Invoke("UpdateInboundUserCount", new object[] {
                        queueNo,
                        inboundUserCount,
                        inboundUserCountSpecified});
            return ((MsCrmResult)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateInboundUserCountAsync(string queueNo, int inboundUserCount, bool inboundUserCountSpecified) {
            this.UpdateInboundUserCountAsync(queueNo, inboundUserCount, inboundUserCountSpecified, null);
        }
        
        /// <remarks/>
        public void UpdateInboundUserCountAsync(string queueNo, int inboundUserCount, bool inboundUserCountSpecified, object userState) {
            if ((this.UpdateInboundUserCountOperationCompleted == null)) {
                this.UpdateInboundUserCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInboundUserCountOperationCompleted);
            }
            this.InvokeAsync("UpdateInboundUserCount", new object[] {
                        queueNo,
                        inboundUserCount,
                        inboundUserCountSpecified}, this.UpdateInboundUserCountOperationCompleted, userState);
        }
        
        private void OnUpdateInboundUserCountOperationCompleted(object arg) {
            if ((this.UpdateInboundUserCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInboundUserCountCompleted(this, new UpdateInboundUserCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/StartNewCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StartNewCall([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string url) {
            this.Invoke("StartNewCall", new object[] {
                        userId,
                        url});
        }
        
        /// <remarks/>
        public void StartNewCallAsync(string userId, string url) {
            this.StartNewCallAsync(userId, url, null);
        }
        
        /// <remarks/>
        public void StartNewCallAsync(string userId, string url, object userState) {
            if ((this.StartNewCallOperationCompleted == null)) {
                this.StartNewCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartNewCallOperationCompleted);
            }
            this.InvokeAsync("StartNewCall", new object[] {
                        userId,
                        url}, this.StartNewCallOperationCompleted, userState);
        }
        
        private void OnStartNewCallOperationCompleted(object arg) {
            if ((this.StartNewCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartNewCallCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAHIBINDEN.Library.Utility")]
    public partial class InboundResult {
        
        private string agentIdField;
        
        private bool statusField;
        
        private bool statusFieldSpecified;
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAHIBINDEN.Library.Utility")]
    public partial class MsCrmResult {
        
        private string crmIdField;
        
        private string extraInformationField;
        
        private bool hasExceptionField;
        
        private bool hasExceptionFieldSpecified;
        
        private string resultField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        public string CrmId {
            get {
                return this.crmIdField;
            }
            set {
                this.crmIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExtraInformation {
            get {
                return this.extraInformationField;
            }
            set {
                this.extraInformationField = value;
            }
        }
        
        /// <remarks/>
        public bool HasException {
            get {
                return this.hasExceptionField;
            }
            set {
                this.hasExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasExceptionSpecified {
            get {
                return this.hasExceptionFieldSpecified;
            }
            set {
                this.hasExceptionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartCallCompletedEventHandler(object sender, StartCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InboundResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InboundResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartCallToAgentCompletedEventHandler(object sender, StartCallToAgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartCallToAgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartCallToAgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InboundResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InboundResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void IsAgentReadyCompletedEventHandler(object sender, IsAgentReadyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAgentReadyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAgentReadyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsCrmResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsCrmResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateCrmStatusCompletedEventHandler(object sender, UpdateCrmStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCrmStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCrmStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsCrmResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsCrmResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartCallToAgentFromKCMCompletedEventHandler(object sender, StartCallToAgentFromKCMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartCallToAgentFromKCMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartCallToAgentFromKCMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InboundResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InboundResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CIFACompletedEventHandler(object sender, CIFACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CIFACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CIFACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsCrmResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsCrmResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartCallMeUrgentCompletedEventHandler(object sender, StartCallMeUrgentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartCallMeUrgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartCallMeUrgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InboundResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InboundResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateInboundUserCountCompletedEventHandler(object sender, UpdateInboundUserCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateInboundUserCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateInboundUserCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsCrmResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsCrmResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartNewCallCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591